// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7T7x7Jjp7-s-hWnFLAg6bJoQ8uLsiVEg',
    appId: '1:789893945993:ios:f047879cdb3e32fe948458',
    messagingSenderId: '789893945993',
    projectId: 'solar-project-backend-6bb4e',
    storageBucket: 'solar-project-backend-6bb4e.firebasestorage.app',
    iosBundleId: 'com.example.solarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7T7x7Jjp7-s-hWnFLAg6bJoQ8uLsiVEg',
    appId: '1:789893945993:ios:f047879cdb3e32fe948458',
    messagingSenderId: '789893945993',
    projectId: 'solar-project-backend-6bb4e',
    storageBucket: 'solar-project-backend-6bb4e.firebasestorage.app',
    iosBundleId: 'com.example.solarApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALGWMLICAKS6K0Bf7W7hU0z80Bvn4OUno',
    appId: '1:789893945993:web:d1e4d4a5b03015a0948458',
    messagingSenderId: '789893945993',
    projectId: 'solar-project-backend-6bb4e',
    authDomain: 'solar-project-backend-6bb4e.firebaseapp.com',
    storageBucket: 'solar-project-backend-6bb4e.firebasestorage.app',
    measurementId: 'G-3PZLXKQ8B8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnsEptmqG17EHPqSUk9xgsNov0W1-TqC8',
    appId: '1:789893945993:android:74977540891c51cf948458',
    messagingSenderId: '789893945993',
    projectId: 'solar-project-backend-6bb4e',
    storageBucket: 'solar-project-backend-6bb4e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALGWMLICAKS6K0Bf7W7hU0z80Bvn4OUno',
    appId: '1:789893945993:web:dbb4126166cb1bf9948458',
    messagingSenderId: '789893945993',
    projectId: 'solar-project-backend-6bb4e',
    authDomain: 'solar-project-backend-6bb4e.firebaseapp.com',
    storageBucket: 'solar-project-backend-6bb4e.firebasestorage.app',
    measurementId: 'G-3TL08VLLX1',
  );

}